### ISSUE TITLE
Add quality threshold for reads

### ISSUE THREAD

**Issue by pockerman** [pockerman/hidden_markov_modeling#13]
We need a quality threshold for every read.
- Affects: json config and some scripts
- disambiguate: when the read is rejected does it get replaced from the reference sequence of simply ignored?

**Comment by colinveal** [comment]
you'll only need to check read quality when performing count for a pileup column. 
when a read is rejected it is dimply ignored, however if all reads are rejected for a base (count = 0) then reference seq will be needed as for any count=0 or gap.
when using quality scores be aware that value of zero indicates that the read maps multiple places and is not a measure of quality. previously we used to keep read that were either 0 or >20

**Comment by pockerman** [comment]
have a look at the implementation here https://github.com/pockerman/hidden_markov_modeling/pull/18/files#diff-fdcbdabfb4ed7222678d0cca85879330R258 
whilst I am doing some debugging :) is this what you mean above?

**Comment by colinveal** [comment]
nearly I think the quality part looks good, we might also want to add mapping quality, I'm going to do a bit of testing in pysam. there a few scenarios i've not thought of, i.e if the pileup.n is 0 ,but there is a read (is_del) then we know that the base is not present and perhaps we shouldn't fill in from fasta, but use '-' instead. However if there isn't a read, then we don't know if deleted, TUF or chance so should fill in from fasta. The read depth should always be the number of accepted reads so may need to be different from pileup.n (perhaps store both).  
Also when we move across a window we may need to ignore '-' in the counting

**Comment by colinveal** [comment]
in pysam you can:
pileupcolumn.set_min_base_quality(minqual)
and use 
pileupcolumn.get_num_aligned() to get the count using the min base quality no need to iterate

also it says
pileupcolumn.n is depracated
use .nsegments instead

**Comment by colinveal** [comment]
other filtering we can do on the pileup command, except for mapping quality

**Comment by colinveal** [comment]
I've just noticed that for deletions within a read (is_del), the read is still counted for that position:
14284446 nsegments:16 num_aligned:16
[42, 42, 42, 42, 40, 42, 42, 42, 42, 42, 42, 42, 42, 40, 42, 42] mapping qual
[37, 34, 41, 34, 69, 38, 35, 38, 39, 40, 36, 38, 36, 0, 38, 33] base qual
['*', '*', '*', '*', '*', '*', '*', '*', '*', '*', '*', '*', '*', '*', '*', '*'] query_sequence (seems to use * not N as stated in manual):

reads viewed on reference:
[IGV.pdf](https://github.com/pockerman/hidden_markov_modeling/files/4392624/IGV.pdf)

**Comment by colinveal** [comment]
just to note that when using add_indels to get_query_sequences it will also add a negative number before on the base before a deletion, will need to remove these before gc counts

**Comment by pockerman** [comment]
hmmmm....I sounds like  we need to reconsider how we retrieve the data from BAM....

**Comment by colinveal** [comment]
> hmmmm....I sounds like we need to reconsider how we retrieve the data from BAM....

i think it is ok at the moment, as most is handled on the pileupcolumn
