### ISSUE TITLE
Add save/load window data as json

### ISSUE THREAD

**Issue by pockerman** [pockerman/hidden_markov_modeling#15]

**Comment by colinveal** [comment]
or pickle, or drop into a database (how about a jsonb in postgres?)

**Comment by pockerman** [comment]
I don't mind any or both whatever you think is useful...by the way I had in mind more to be able to save  the simulation status when running on the cluster for post processing. Can you deploy a DB on the cluster? If not provisioning for a DB is sth you think worth the trouble?
