### ISSUE TITLE
Create HMM simulation with three common states

### ISSUE THREAD

**Issue by pockerman** [pockerman/hidden_markov_modeling#16]
Develop train/fit-predict pipeline with pomgranate.HMM model and our data where the model has three states NORMAL-INSERT-DELETE

**Comment by colinveal** [comment]
there are some hmm models out there for this already (for copy number variation not TUF).
https://academic.oup.com/biostatistics/article/14/3/600/260213

this one isn't for read depth but could be useful:
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2045149/

**Comment by pockerman** [comment]
I have been able to find sth like 4-5 publications of HMM application related to CNVs none so far related to TUF

**Comment by colinveal** [comment]
> I have been able to find sth like 4-5 publications of HMM application related to CNVs none so far related to TUF

no there won't be any of TUF, we'll adapt the CNV ones
